services:
  - type: web
    name: adrianlab-external-render
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASE_URL
        value: https://adrianlab.vercel.app
      - key: PORT
        fromService:
          type: web
          name: adrianlab-external-render
          property: port

